Bitbucket 6 compatibility
voxpupuli/puppet-stash pull request #189
Opened 2019-12-23 17:41 UTC by dickp

#### Pull Request (PR) description

Adds compatibility with Bitbucket 6, including on Ubuntu 18.04

#### This Pull Request (PR) fixes the following issues

2019-12-23 19:51 UTC, bastelfreak commented on Gemfile
> +  gem 'overcommit', '>= 0.39.1', '<= 0.47.0',  :require => false
Could you explain why you pinned to to < 0.48?

2019-12-23 19:52 UTC, bastelfreak commented on Gemfile
> +  gem 'activesupport', '~> 5.0',                                    :require => false
why do we need the activerecord gem?

2019-12-23 19:54 UTC, bastelfreak commented on Gemfile
> +  gem 'puppet-blacksmith', '< 5.0.0',          :require => false
why do you pin this to < 5?

2019-12-23 19:58 UTC, bastelfreak commented on manifests/backup.pp
> +  cron { 'Backup Bitbucket':
do we run into issues if we change the resource title? this will create another cronjob but the old one still exists?

2019-12-23 20:02 UTC, bastelfreak commented on manifests/params.pp
> +      if $facts['os']['release']['full'] == '18.04' {
should we update the condition and just check if systemd is the used init_system? `facts['systemd']` for example or `facts['service_provider']`

2019-12-23 20:03 UTC, bastelfreak commented on manifests/service.pp
> +  if $stash::product == 'bitbucket' {
you can make this block a bit more readable by using the selector pattern:
https://puppet.com/docs/puppet/6.10/lang_conditional.html#reference-1138

2019-12-23 20:06 UTC, bastelfreak commented on templates/bitbucket.properties.erb
> +server.context-path=<%= scope['stash::context_path'] %>
can you please migrate the new template to an epp template?

2019-12-23 20:08 UTC, bastelfreak commented on templates/stash.service.erb
> +<%- if scope.lookupvar('extra_environment') -%>
you don't need to call a function to access variables in an erb template:
```suggestion
<%- if @extra_environment -%>
```

otherwise feel free to convert the while to an epp template.

2019-12-23 20:12 UTC, bastelfreak commented
Hi @dickp. thanks for the PR. I had a few minutes and gave this a quick review. Please join us on our IRC chat #voxpupuli on freenode or our slack at http://slack.puppet.com/ if you've any questions (or respond here in the PR).

2019-12-24 12:59 UTC, dickp commented on Gemfile
> +  gem 'overcommit', '>= 0.39.1', '<= 0.47.0',  :require => false
My devel machine was running Ubuntu 16.04, and the version of ruby on that is 2.3.  All of the version pinning is to persuade bundler to not try to install packages such as zeitwerk that require ruby >= 2.4

2019-12-24 12:59 UTC, dickp commented on Gemfile
> +  gem 'activesupport', '~> 5.0',                                    :require => false
It's to force a dependency to use a version compatible with ruby 2.3

2019-12-24 13:00 UTC, dickp commented on Gemfile
> +  gem 'puppet-blacksmith', '< 5.0.0',          :require => false
Again, ruby 2.3 dependency

2019-12-24 13:00 UTC, dickp commented on manifests/backup.pp
> +  cron { 'Backup Bitbucket':
Good catch.  I tried to avoid breaking updates, but this one slipped through

2019-12-24 13:01 UTC, dickp commented on manifests/params.pp
> +      if $facts['os']['release']['full'] == '18.04' {
Probably.  I was trying to make minimal changes.

2019-12-24 13:01 UTC, dickp commented on templates/bitbucket.properties.erb
> +server.context-path=<%= scope['stash::context_path'] %>
Could do, but probably not for a couple of weeks.  I used .erb as I was following the existing coding style.

2020-01-10 21:26 UTC, dickp commented on Gemfile
> +  gem 'overcommit', '>= 0.39.1', '<= 0.47.0',  :require => false
I've removed the Gemfile changes to allow ruby 2.3 to work.  I'll just have to make sure I don't delete the Gemfile.lock

2020-01-10 21:26 UTC, dickp commented on manifests/backup.pp
> +  cron { 'Backup Bitbucket':
I've reverted this change too

2020-01-10 21:27 UTC, dickp commented on manifests/service.pp
> +  if $stash::product == 'bitbucket' {
Done

2020-01-10 21:27 UTC, dickp commented on templates/bitbucket.properties.erb
> +server.context-path=<%= scope['stash::context_path'] %>
Done

2020-01-10 21:27 UTC, dickp commented on templates/stash.service.erb
> +<%- if scope.lookupvar('extra_environment') -%>
Done

2020-01-11 12:32 UTC, dhoppe requested changes

2020-01-11 12:32 UTC, dhoppe commented on Gemfile
> +  gem 'beaker-vagrant',                     :require => false
Is this gem really necessary? We use Docker for acceptance test and ˋˋˋvoxpupuli/modulesync_configˋˋˋ will remove this during its next execution.

2020-01-11 12:32 UTC, dhoppe commented on manifests/config.pp
> +                  Class['stash::install'],
Please fix the indentation.

2020-01-11 12:32 UTC, dhoppe commented on manifests/config.pp
> +                  Class['stash::install'],
Please fix the indentation.

2020-01-11 12:32 UTC, dhoppe commented on Gemfile
> +  gem 'beaker-vagrant',                     :require => false
Is this gem really necessary? We use Docker for acceptance tests and ˋˋˋvoxpupuli/modulesync_configˋˋˋ will remove this during its next execution.

2020-01-11 12:32 UTC, dhoppe commented on manifests/config.pp
> +                  Class['stash::install'],
Please fix the nindentation.

2020-01-11 12:32 UTC, dhoppe commented on manifests/config.pp
> +                  Class['stash::install'],
Please fix the nindentation.

2020-01-11 12:32 UTC, dhoppe commented on manifests/config.pp
> +                  Class['stash::install'],
Please fix the nindentation.

2020-01-25 10:20 UTC, dickp commented on Gemfile
> +  gem 'beaker-vagrant',                     :require => false
I added it before I realise the acceptance tests hadn't run on vagrant in years.  I've taken it out again now.

2020-01-25 10:20 UTC, dickp commented on manifests/config.pp
> +                  Class['stash::install'],
Done

2020-01-30 21:16 UTC, bastelfreak commented
thanks for all the work!

2020-01-30 21:16 UTC, merged