fix ruby bin dir and remove unnecessary vars and code blocks
voxpupuli/puppet-stash pull request #194
Opened 2020-08-26 23:28 UTC by SimonHoenscheid

2020-08-27 17:28 UTC, igalic requested changes
this either need to be two or three separate pull requests, or this pull request needs better commit messages, aaaaand an overall better description than: No description given.

2020-09-06 17:30 UTC, SimonHoenscheid commented
@igalic I will rework this one

2020-09-23 19:31 UTC, bastelfreak approved these changes

2020-09-23 19:37 UTC, SimonHoenscheid commented
@igalic if you are fine with the PR, this can be merged

2020-09-23 20:45 UTC, igalic commented on manifests/facts.pp
>  ) inherits stash {
we should probably get rid of this inherit

2020-09-23 20:47 UTC, igalic approved these changes

2020-09-23 20:47 UTC, merged